#!/usr/bin/env python3
"""
Cron execution wrapper: runs a command and logs it to the dashboard database.

Usage:
  /usr/bin/python3 /home/corti/dashboard-server/backend/scripts/cron_log.py <command> [args...]

Example crontab entry (generated by the dashboard):
  */5 * * * * /usr/bin/python3 /home/corti/dashboard-server/backend/scripts/cron_log.py bash /home/corti/Escritorio/hello_world.sh
"""
import os
import sys
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path

# Locate project root (this file is at <root>/backend/scripts/cron_log.py)
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

from backend.database import SessionLocal
from backend.models.script import ScriptExecution
from backend.models.execution_log import ExecutionLog


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: cron_log.py <command> [args...]", file=sys.stderr)
        sys.exit(1)

    cmd_parts = sys.argv[1:]

    # Normalize python executable: "python" / "python3" literals fail on systems
    # that only have one or the other. Replace with the interpreter running this
    # wrapper — it's always the correct one (venv or system).
    if cmd_parts and cmd_parts[0] in ('python', 'python3'):
        cmd_parts[0] = sys.executable

    # Detect the primary script path (first absolute path in cmd)
    script_path: str = " ".join(cmd_parts)
    for part in cmd_parts:
        if part.startswith("/"):
            script_path = part
            break

    db = SessionLocal()
    exec_id: int | None = None
    start = datetime.now(timezone.utc)
    t0 = time.monotonic()

    try:
        # Create ScriptExecution record (stream-style: output filled in after)
        exe = ScriptExecution(
            script_path=script_path,
            started_at=start,
            triggered_by="cron",
            run_as_root=False,
            output="",
        )
        db.add(exe)
        db.commit()
        db.refresh(exe)
        exec_id = exe.id

        # Run the wrapped command
        result = subprocess.run(
            cmd_parts,
            capture_output=True,
            text=True,
            timeout=3600,
        )

        full_output = result.stdout
        if result.stderr:
            full_output += "\n[stderr]\n" + result.stderr

        elapsed = time.monotonic() - t0
        end = datetime.now(timezone.utc)

        # Update ScriptExecution with result
        exe.ended_at = end
        exe.exit_code = result.returncode
        exe.output = full_output
        db.commit()

        # Write ExecutionLog summary (used by the Logs view)
        log = ExecutionLog(
            script_path=script_path,
            username="cron",
            started_at=start,
            ended_at=end,
            exit_code=result.returncode,
            duration_seconds=round(elapsed, 3),
            output_summary=full_output[:500] if full_output else None,
        )
        db.add(log)
        db.commit()

    except Exception as exc:  # pragma: no cover
        elapsed = time.monotonic() - t0
        end = datetime.now(timezone.utc)
        err_msg = f"cron_log wrapper error: {exc}"
        try:
            if exec_id is not None:
                db.query(ScriptExecution).filter(
                    ScriptExecution.id == exec_id
                ).update({"ended_at": end, "exit_code": -1, "output": err_msg})
            log = ExecutionLog(
                script_path=script_path,
                username="cron",
                started_at=start,
                ended_at=end,
                exit_code=-1,
                duration_seconds=round(elapsed, 3),
                output_summary=err_msg[:500],
            )
            db.add(log)
            db.commit()
        except Exception:
            pass
        print(err_msg, file=sys.stderr)
        sys.exit(1)
    finally:
        db.close()


if __name__ == "__main__":
    main()
